name: build-rootfs
on:
  pull_request:
  schedule:
    - cron: '0 8 * * *'
  push:
    branches:
      - "main"
  workflow_dispatch:

jobs:
  build-and-push:
    name: Build and push rootfs
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
      options: --privileged
      volumes:
        - "/:/host"
    permissions:
      contents: read
      packages: write
      id-token: write
    strategy:
      fail-fast: false

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Test container
        shell: bash
        run: |
          sed -i "s/[options]/[options]\nSigLevel = Never"
          sed -i '72i[arkane]\nServer = https://repo.arkanelinux.org/$repo/os/$arch' /etc/pacman.conf
          sed -i '74i[arkane-cauldron]\nServer = https://repo.arkanelinux.org/$repo/os/$arch' /etc/pacman.conf

          pacman-key --init
          pacman -Sy --noconfirm archlinux-keyring
          pacman -Syu --noconfirm
          pacman -S --noconfirm base base-devel arkane-keyring arkdep
