name: build-rootfs
on:
  pull_request:
  schedule:
    - cron: '0 8 * * *'
  push:
    branches:
      - "main"
  workflow_dispatch:

jobs:
  build-and-push:
    name: Build and push rootfs
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    strategy:
      fail-fast: false

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Create virtual btrfs filesystem
        shell: bash
        run: |
          truncate --size=10G builder.img
          mkfs.btrfs builder.img
          mkdir builder
          sudo mount -t btrfs -o defaults,noatime ./builder.img ./builder
          cp -r arkdep-build.d builder/

      - name: Build rootfs in container
        uses: addnab/docker-run-action@v3
        with:
          image: archlinux:latest
          options: -v /:/host
          run: |
            cd /home/runner/work/magical-timesink/builder

            sed -i "s/Required DatabaseOptional/Never/g" /etc/pacman.conf
            sed -i '72i[arkane]\nServer = https://repo.arkanelinux.org/$repo/os/$arch' /etc/pacman.conf
            sed -i '74i[arkane-cauldron]\nServer = https://repo.arkanelinux.org/$repo/os/$arch' /etc/pacman.conf

            pacman-key --init
            pacman -Sy --noconfirm archlinux-keyring
            pacman -Syu --noconfirm
            pacman -S --noconfirm base base-devel btrfs-progs arch-install-scripts device-mapper arkane-keyring arkdep

            arkdep-build timesink
            cp target/*.zst ./timesink.tar.zst

